CREATE TABLE todos (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    completed TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);